### ISSUE TITLE
Followers module has incorrect values for the "Since" column

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPressCom-Stats-iOS#251]
![screen shot 2015-05-05 at 15 20 30](https://cloud.githubusercontent.com/assets/518232/7473377/0947e942-f33b-11e4-80ea-b2e3135f9633.png)

Web version:
![screen shot 2015-05-05 at 15 27 14](https://cloud.githubusercontent.com/assets/518232/7473416/4f28a32a-f33b-11e4-8e51-8fca3675e5e4.png)

**Comment by rachelmcr** [comment]
This issue also affects the "Latest Post Summary" module, which shows an incorrect value for the number of days since the latest post was published.

App version (from WPiOS 6.3.0.20160603.1):

![2016-06-08 11 08 59](https://cloud.githubusercontent.com/assets/8658164/15890877/ad29f118-2d69-11e6-9132-aa72b4815d5a.png)


Web version:

<img width="741" alt="screen shot 2016-06-08 at 11 09 18 am" src="https://cloud.githubusercontent.com/assets/8658164/15890864/9b82c34a-2d69-11e6-8e0b-26ac2955cd3f.png">

**Comment by astralbodies** [comment]
Closing issue and migrating to new repo.
