### ISSUE TITLE
Support RTL languages properly

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#331]
Related issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/4346

Fix the stats screens to support RTL properly.

**Comment by astralbodies** [comment]
Ping @koke just because you have renewed interest in solidifying our RTL support.

**Comment by koke** [comment]
🤔  That issue seems to be fixed. The only pending RTL fixes on Stats that I'm aware of are on https://github.com/wordpress-mobile/WordPress-iOS/issues/6432#issuecomment-278448920:

> Labels in site stats (e.g. titles in the Posts & Pages module, usernames in Comments and Followers modules, country names in the Countries module) are aligned to the left instead of right:

![screen shot 2017-02-08 at 8 02 22 pm](https://cloud.githubusercontent.com/assets/8658164/22755086/90d66316-ee39-11e6-9038-f8fbdeb469c9.png)

**Comment by koke** [comment]
The `SiteStats` storyboard scares me 😬 
I've tested a bit and most things look good, but:
- A few labels need to change their alignment from left to natural
- Everything that's right-aligned would, in theory, need to be flipped. But those seem to be only the values that have a width that fits the content, so alignment isn't really relevant.

**Comment by astralbodies** [comment]
Closing issue and migrating to new repo.
